### PR TITLE
Example revision

### PR DESCRIPTION
**Pull request by Ayoub-Farah**
Correct errors present in some main.cpp example file, add library.json to have platformIO compatibility, and more detailed documentation for example. 
A general readme was added to have a direct link to all the example.

### CODE REVIEW

**Comment by Ayoub-Farah** [comment]
closes #1

**Comment by jalinei** [comment]
In example SPIN/blinky
example not building without uncommenting 
CONFIG_OWNTECH_COMMUNICATION_ENABLE_RS485=y
CONFIG_OWNTECH_COMMUNICATION_ENABLE_SYNC=y
It seems to be due to the fact that SCONS builds the library. We should find a fix prior to releasing the example library.

**Comment by jalinei** [comment]
//--------------SETUP FUNCTIONS-------------------------------

/**
 * This is the setup routine.
 * It is used to call functions that will initialize your spin, twist, data and/or tasks.
 * In this example, we setup the version of the spin board and a background task.
 * The critical task is defined but not started.
 */
void setup_routine()
{
    // Setup the hardware first
    spin.version.setBoardVersion(TWIST_v_1_1_2);

setBoardVersion should not be linked to TWIST in SPIN examples. 
also please add yourself as an author for each example that you've modified. 
Please add credits for other authors in library.json.

**Comment by jalinei** [comment]
image

Multiple warnings are shown in vscode quick toolbar.

**Comment by jalinei** [comment]
I would like to add Hello World vanilla example from core into SPIN example as well if possible. 
Also from an ergonomic perspective, I would like that we reorder library.json so that example are shown with an increasing level of complexity in the GUI. 

image

**Comment by jalinei** [comment]
We need to make a change in CMakeList.txt 
https://github.com/owntech-foundation/Core/blob/main/zephyr/CMakeLists.txt
In order to include any .conf or .overlay file present in src/ 
As such we'll be able to add certain CONFIG instructions for a specific example. 
@cfoucher-laas I would appreciate your help with that, as I'm not familiar with CMakeList syntax yet.

**Pull request merged**
